### ISSUE TITLE
Bring back to life?

### ISSUE THREAD

**Issue by bossjones** [chrishoffman/go-sensu-client#1]
Hey man!

I think you're really on to something here. Using a sensu-client that has been compiled in go can work REALLY well on systems such as a raspberry pi that has low resources. My ruby is much better than my golang, but I would love to help bring some life into this project again. Curious what complications you ran into ? Were there not enough libraries out there to support something like this in the past? How can I help?

**Comment by chrishoffman** [comment]
I was just prototyping here.  My main use case was Windows since I didn't want to carry around the Ruby runtime on Windows.  I made some good progress on the basic foundation of implementation and got basic keepalive working but ended up moving away from Sensu (not because Sensu isn't an awesome project).  Feel free to fork and play around with it, I'd love to see where you get.
